services:
  free-games-bot:
    image: ghcr.io/andrea-01/free-games-bot:latest
    container_name: free-games-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
